---
published: true
title: "Java script ES6💫 중급🔥 ✍️ (5) Promise"
permalink: /cs/test
tags:
  - [CS]

navigation: true
toc: true
toc_sticky: true

date: 2022-04-01
last_modified_at: 2022-04-01
---

![]()



# 16. Promise

## 16-1. 소개

#### Callback Hell

- id가 'btn'인 button을 클릭하면 서버에 users 리스트를 가져오는 요청을 하고,
- 성공하면 list의 세번째 user의 정보를 다시 요청하여
- 성공하면 user의 profileImage url값을 가져다가 image 태그로 표현하고,
- 이 image를 클릭하면 해당 이미지를 제거.

```js
const script= document.createElement('script')
script.src= 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'
document.body.appendChild(script)

document.body.innerHTML += '<button id="btn">클릭</button>'
document.getElementById('btn').addEventListener('click', function (e) {
  $.ajax({
    method: 'GET',
    url: 'https://api.github.com/users?since=1000',
    success: function (data) {
      var target = data[2]
      $.ajax({
        method: 'GET',
        url: 'https://api.github.com/user/' + target.id,
        success: function (data) {
          var _id = 'img' + data.id
          document.body.innerHTML += '<img id="' + _id + '" src="' + data.avatar_url + '"/>'
          document.getElementById(_id).addEventListener('click', function (e) {
            this.remove()
          })
        },
        error: function (err) {
          console.error(err)
        }
      })
    },
    error: function (err) {
      console.error(err)
    }
  })
})
```

이렇게 옆으로 파고드는 구조보다는 순차적인 시퀀스가 좋다.<br/>
그래서 등장한 게 `Promise`


#### Promise

```js
document.body.innerHTML = '<button id="btn">클릭</button>'
document.getElementById('btn').addEventListener('click', function (e) {
    fetch('https://api.github.com/users?since=1000')
    .then(function (res) { return res.json() })
    .then(function (res) {
        var target = res[2]
        return fetch('https://api.github.com/user/' + target.id)
    })
    .then(function (res) { return res.json() })
    .then(function (res) {
        var _id = 'img' + res.id
        document.body.innerHTML += '<img id="' + _id + '" src="' + res.avatar_url + '"/>'
        document.getElementById(_id).addEventListener('click', function (e) {
            this.remove()
        })
    })
    .catch(function (err) {
        console.error(err)
    })
})
```


.then을 사용해서 동작이 끝나면 다음 동작으로, 순차적인 흐름으로 변경

#### Promise를 반환하면서 JSON parsing을 자동으로 해주는 library (axios) 활용시

```js
const script= document.createElement('script')
script.src= 'https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js'
document.body.appendChild(script)

document.body.innerHTML += '<button id="btn">클릭</button>'
document.getElementById('btn').addEventListener('click', function (e) {
    axios.get('https://api.github.com/users?since=1000')
    .then(function (res) {
        var target = res.data[2]
        return axios.get('https://api.github.com/user/' + target.id)
    })
    .then(function (res) {
        var _id = 'img' + res.data.id
        document.body.innerHTML += '<img id="' + _id + '" src="' + res.data.avatar_url + '"/>'
        document.getElementById(_id).addEventListener('click', function (e) {
            this.remove()
        })
    })
    .catch(function (err) {
        console.error(err)
    })
})
```

.then(function (res) { return res.json() })<br/>
반복되는 이 부분을 axios로 한번에 처리

then으로 콜백함수를 계속 넘기는 패턴은 아직 남아있지만, then 사용 전보다는 콜백지옥을 해결.


## 16-2. 상세

<img src="/assets/images/JS_class_extends.png" /><br/>

then과 catch 메소드가 `prototype` 안에 있다.<br/>

promise를 하나의 클래스로 생각을 하면,<br/>
promise는 생성자 함수로 (Class로) 만든 **인스턴스**로서 prototype 상으로 then과 catch 메소드에 접근이 된다.<br/>
그 외의 all, reject, resolve 이런 메소드는 promise 자체에 내장된 `static 메소드`!<br/>

Promise.all **(O)** <br/>
new Promise().all **(X)** 인스턴스로 만들면 `접근 불가능` <br/>


### 16-2-1. Promise Status

비동기 처리를 해두면 알아서 상태 처리를 해서 돌려준다.
 
- unnsettled (미확정) 상태: pending. thenable하지 않다.
어떤 요청이 있어서 이게 비동기적으로 처리가 될건데, 그 비동기처리 과정이 끝나기 전 상태

- settled (확정) 상태: resolved. thenable한 상태.
비동기 처리가 끝나고 나면 상태가 settled로 바뀐다
   - fulfilled (성공)
  - rejected (실패)

<br/>

const a = new Promise() <br/>
이렇게만 해도 인스턴스를 만들 수 있지만 매개변수를 넘길 수 있음. <br/>

```js
const a = new Promise(function(성공시호출함수, 실패시호출함수) {
  // 실제 동작을 구현하고,
  // 이 동작이 성공하면 성공시호출함수,
  // 실패하면 실패시호출함수를 내부에서 구현해두면 된
})
```

그렇게 보면

```js
const promiseTest = param => new Promise((resolve, reject) => {
	setTimeout(() => {
		if (param) {
			resolve("해결 완료")
		} else {
			reject(Error("실패!!"))
		}
	}, 1000)
})

```

promiseTest라는 함수는 param을 받아서, <br/>
Promise의 인스턴스를 만든 걸 반환하고 있다<br/>

그럼 promiseTest에 param을 넘겨서 실행한 결과값은 아래와 동일.


```js
const a = new Promise(function(성공시호출함수, 실패시호출함수) {
  // 실제 동작을 구현하고,
  // 이 동작이 성공하면 성공시호출함수,
  // 실패하면 실패시호출함수를 내부에서 구현해두면 된
})
```


```js
const promiseTest = param => new Promise((resolve, reject) => {
	setTimeout(() => {
		if (param) {
			resolve("해결 완료")
		} else {
			reject(Error("실패!!"))
		}
	}, 1000)
})

const a = promiseTest(true)
a
// Promise {<resolved>: "해결 완료"}
```

new Promise로 **인스턴스를 만드는 순간에 `내부함수를 실행`**한다. <br/>
그럼 그 내부에서는,<br/>
setTimeout을 돌면서 1초 뒤에 안에 있는 내용을 실행<br/>

그때에 넘겨받은 **true**로 인해 **`resolve`가 호출**됐고, <br/>
resolve에 의해서 promise의 전체상태가 unsettled에서 `settled`로 변경되고<br/>
그 결과가 fulfilled가 됨<br/>


```js
const promiseTest = param => new Promise((resolve, reject) => {
	setTimeout(() => {
		if (param) {
			resolve("해결 완료")
		} else {
			reject(Error("실패!!"))
		}
	}, 1000)
})

const b = promiseTest(false)
// Uncaught (in promise) Error: 실패!!
b
// Promise {<reject>: "실패!!"}
```

성공시에는 resolved라고 나왔는데 왜 reject라고 나올까? <br/>
=> 브라우저마다 다름!<br/>

크롬에서는 이렇게 나오지만 파이어폭스에서는 fulfilled라고 나옴.<br/>

성공했음을 대체할 때도 있고, unnsettled에서 settled로 넘어갔음을 표시할 때도 있으니 문맥에 따라 파악하는 수밖에 없음.



```js
const testRun = param => promiseTest(param)
// promiseTest로 만든애는 promise의 인스턴스.
// 인스턴스이기 때문에 prototype상의 then과 catch를 쓸 수 있다

  .then(text => { console.log(text) })
  .catch(error => { console.error(error) })

// resolve가 실행된 순간 then이 실행
// reject가 실행되면 catch로

```

 

```js
const promiseTest = (param, delay) => new Promise((resolve, reject) => {
	setTimeout(() => {
		if (param) {
			resolve("해결 완료")
		} else {
			reject(Error("실패!!"))
		}
	}, delay)
})
const testRun = param => promiseTest(param, delay)

  .then(text => { console.log(text) })
  .catch(error => { console.error(error) })

const a = testRun(true,1000)
const b = testRun(false,2000)
// 해결완료
// 1초 후
// Error: 실패!! at setTimeout

```

그 후 변수들을 다시 호출하면

```js
a
// Promise{ resolved: undefiled}
b
// Promise{ resolved: undefiled}
```
a는 여전히 promise의 인스턴스로 resolved 상태<br/>
b도 여전히 promise의 인스턴스로 resolved 상태<br/>

b는 catch로 에러가 난 상태인데도 왜 resolved지? <br/>
반환한 것 없이 그냥 resolve처리를 시킨것.<br/>


```js
a.then(() => { return 1; })
// Promise { <resolved>: 1 }
a.then(res => { console.log(res) })
// undefined
// Promise { <resolved>: undefined }

a.then(() => { return 1; })
.then(res => { console.log(res) })
1
// Promise { <resolved>: undefined }

```

끝난 것 같지만 다시 내가 원할 때 이어서 then을 또 할 수 있다.<br/>

한번 promise는 영원한 promise! 영원히 이어서 갈 수 있다<br/>

promise를 중단시킬 수 없다는 점에서 한계.



### 16-2-2. 문법

- `new Promise(function)`
- `.then()`, `.catch()`는 언제나 promise를 반환한다.

```js
const executer = (resolve, reject) => { ... }
const prom = new Promise(executer)

const onResolve = res => { ... }
const onReject = err => { ... }

// (1)
prom.then(onResolve, onReject)

// (2)
prom.then(onResolve).catch(onReject)
```


(1) <br/>
prom.then(onResolve, onReject)<br/>
then안에서 성공시 함수, 실패시 함수를 만들 수 있다<br/>

```js
const testRun = (param,delay) => promiseTest(param, delay)

  .then(text => { console.log(text) },
  error => { console.error(error)}
);

```

then catch를 나눠서 할 수도 있고, 아래처럼 한번에 할 수도 있음.


```js
new Promise((resolve, reject) => { ... })
.then(res => { ... })
.catch(err => { ... })
```



```js
const simplePromiseBuilder = value => {
  return new Promise((resolve, reject) => {
    if(value) { resolve(value) }
    else { reject(value) }
  })
}
// value를 넘겨받고 promise의 인스턴스를 반환


simplePromiseBuilder(1)
  .then(res => { console.log(res) })
  .catch(err => { console.error(err) })

simplePromiseBuilder(0)
  .then(res => { console.log(res) })
  .catch(err => { console.error(err) })
```

전혀 simple하지 않네! then이 똑같은 내용을 반복하고 있어.


```js
const simplePromiseBuilder2 = value => {
  return new Promise((resolve, reject) => {
    if(value) { resolve(value) }
    else { reject(value) }
  })
  .then(res => { console.log(res) })
  .catch(err => { console.error(err) })
}

simplePromiseBuilder2(1)
simplePromiseBuilder2(0)
```
이렇게 애초에 promise를 반환할 때, 그 안에 then과 catch를 반환시키면 된다.

```js
simplePromiseBuilder2(0).then(res => {console.log('이어서 하고싶으면 함수호출시에 적으세염')})

const a = simplePromiseBuilder2(1)
a.them(res => { console.log('리턴해주면 계속 덴덴덴 갈 수 있어요')})

```



```js
const prom = new Promise((resolve, reject) => {
  resolve()
  reject()
  console.log('Promise')
})

// Promise 출력 된다


prom.then(() => {
  console.log('then')
})

prom.catch(() => {
  console.log('catch')
})

console.log('Hi!')

// Promise
// Hi
// then
```
출력순서

- 1) Promise
- 2) Hi
- 3) then

실행 Queue : 어떤 작업을 수행하고, 그 다음 이어서 수행하고.... <br/>

전체소스 실행하는 과정에서 Promise 인스턴스의 함수도 같이 실행되었다.<br/>
-> 그로인해 pending에서 fulfilled가 됨 <br/>
-> fulfilled가 되면서 then함수가 queue에 추가됨.<br/>
-> 계속 전체소스실행이 끝나고 나서<br/>
(하나의 큐 끝)<br/>
-> 다음번큐에 있는 then함수가 실행됨.<br/>

=> reject는 무시되었네??


```js
const prom = new Promise((resolve, reject) => {
  reject()
  resolve()
  console.log('Promise')
})

prom.then(() => {
  console.log('then')
})

prom.catch(() => {
  console.log('catch')
})

console.log('Hi!')

// Promise
// Hi
// catch
```

순서를 바꾸면? <br/>
이번엔 then으로 안가고 catch로만 왔따!<br/>

=><br/>
1. then이나 catch 구문은 실행큐에 후순위로 등록되고 실행된다
2. promise 인스턴스에 넘긴 함수 내부에서는, resolve나 reject 둘 중에 먼저 호출한 것만 실제로 실행된다.
3. 사실은 실제로 실행되는 게 아니라, 실행은 둘다 되는데, pending 상태일 때만 의미가 있기 때문에 2번과 같은 결과가 나온 것


```js
const prom = new Promise((resolve, reject) => {
  reject()
  resolve()
  console.log('Promise')
})
prom.then(() => {
  console.log('then')
})

prom.catch(() => {
  console.log('catch')
})

console.log('Hi!')
```

### 16-2-3. 확장 Promise 만들기

1. `Promise.resolve`, `Promise.reject`

```js
Promise.resolve(42)
.then(res => { console.log(res) })
.catch(err => { console.error(err) })

Promise.reject(12)
.then(res => { console.log(res) })
.catch(err => { console.error(err) })
```

2. thenable 객체

```js
const thenable = {
  then (resolve, reject) {
    resolve(33)
  }
}
const prom = Promise.resolve(thenable)
prom.then(res => { console.log(res) })
```

```js
const thenable = {
  then (resolve, reject) {
    reject(33)
  }
}
const prom = Promise.resolve(thenable)
prom.catch(err => { console.log(err) })
```

### 16-2-4. Promise Chaning (then, catch에서 return)

```js
new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('첫번째 프라미스')
  }, 1000)
}).then(res => {
  console.log(res)
  return '두번째 프라미스'
}).then(res => {
  console.log(res)
  return new Promise((resolve, reject) => {
    setTimeout(() => {
          resolve('세번째 프라미스')
    }, 1000)
  })
}).then(res => {
  console.log(res)
  return new Promise((resolve, reject) => {
    setTimeout(() => {
          reject('네번째 프라미스')
    }, 1000)
  })
}).then(res => {
  console.log(res)
}).catch(err => {
  console.error(err)
  return new Error('이 에러는 then에 잡힙니다.')
}).then(res => {
  console.log(res)
  throw new Error('이 에러는 catch에 잡힙니다.')
}).then(res => {
  console.log('출력 안됨')
}).catch(err => {
  console.error(err)
})
```

### 16-2-5. Error Handling

```js
asyncThing1()
.then(asyncThing2)
.then(asyncThing3)
.catch(asyncRecovery1)
.then(asyncThing4, asyncRecovery2)
.catch(err => { console.log("Don't worry about it") })
.then(() => { console.log("All done!") })
```

![에러 핸들링](https://raw.githubusercontent.com/js-jsm/es6js/master/15%20%ED%94%84%EB%9D%BC%EB%AF%B8%EC%8A%A4/promise_chaining.png)

### 16-2-6. Multi Handling

#### 1. `Promise.all()`

- iterable의 모든 요소가 fulfilled되는 경우: 전체 결과값들을 배열 형태로 then에 전달.
- iterable의 요소 중 일부가 rejected되는 경우: 가장 먼저 rejected 되는 요소 '하나'의 결과를 catch에 전달.

```js
const arr = [
	1,
	new Promise((resolve, reject) => {
		setTimeout(()=> {
			resolve('resolved after 1000ms')
		}, 1000)
	}),
	'abc',
	() => 'not called function',
	(() => 'IIFE')()
]

Promise.all(arr)
.then(res => { console.log(res) })
.catch(err => { console.error(err) })
```

```js
const arr = [
	1,
	new Promise((resolve, reject) => {
		setTimeout(()=> {
			reject('rejected after 1000ms')
		}, 1000)
	}),
	'abc',
	()=> 'not called function',
	(()=> 'IIFE')()
]

Promise.all(arr)
.then(res => { console.log(res) })
.catch(err => { console.error(err) })
```


#### 2. `Promise.race()`

- iterable의 요소 중 가장 먼저 fulfilled / rejected되는 요소의 결과를 then / catch에 전달.

```js
const arr = [
	new Promise(resolve => {
		setTimeout(()=> { resolve('1번요소, 1000ms') }, 1000)
	}),
	new Promise(resolve => {
		setTimeout(()=> { resolve('2번요소, 500ms') }, 500)
	}),
	new Promise(resolve => {
		setTimeout(()=> { resolve('3번요소, 750ms') }, 750)
	})
]
Promise.race(arr)
.then(res => { console.log(res) })
.catch(err => { console.error(err) })
```

```js
const arr = [
	new Promise(resolve => {
		setTimeout(()=> { resolve('1번요소, 0ms') }, 0)
	}),
	'no queue'
]
Promise.race(arr)
.then(res => { console.log(res) })
.catch(err => { console.error(err) })
```

> 참고: [ES2017 Async Function](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/async_function)
